# Generated by Django 5.0 on 2024-11-29 11:17

import django.db.models.deletion
import helios.datatypes
import helios_auth.jsonfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20210123_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_method',
            field=models.CharField(choices=[('simple', 'Simple'), ('quantum-safe', 'Quantum-Safe')], default='simple', max_length=250),
        ),
        migrations.CreateModel(
            name='BallotBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('public_key', helios_auth.jsonfield.JSONField(null=True)),
                ('return_code_server_url', models.CharField(max_length=500)),
                ('shuffle_server_url', models.CharField(max_length=500)),
                ('auditors_urls', helios_auth.jsonfield.JSONField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helios.election')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, helios.datatypes.LDObjectContainer),
        ),
    ]
